controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (0 == HeMan.vy) {
        HeMan.vy += -200
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite, location) {
    game.over(true)
})
let HeMan: Sprite = null
scene.setBackgroundColor(15)
tiles.setTilemap(tilemap`level1`)
HeMan = sprites.create(img`
    ........................
    ....ffffff..............
    ..ff5555f5f.............
    .ff5555f555f............
    .f555ff55555...cc.......
    .ffff5555555f.cdc.......
    .f5555ffff55fcddc.......
    fffffffeeeffcddc........
    ff554ebf44ecddc.........
    f555d41fddecdc..........
    .f55e4dddedccc..........
    ..ffee44e4dde...........
    ...f222244ee............
    ...f2222e2f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
HeMan.setPosition(10, 300)
scene.cameraFollowSprite(HeMan)
controller.moveSprite(HeMan, 150, 0)
HeMan.ay = 350
info.setLife(3)
info.setScore(0)
