controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (0 == HeMan.vy) {
        HeMan.vy += -175
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite, location) {
    game.over(true)
})
let HeMan: Sprite = null
scene.setBackgroundColor(9)
tiles.setTilemap(tilemap`level1`)
HeMan = sprites.create(img`
    ........................
    ....ffffff..............
    ..ff5555f5f.............
    .ff5555f555f............
    .f555ff5555f...cc.......
    .ffff5555555f.cdc.......
    .f5555ffff55fcddc.......
    fffffffeeeffcddc........
    ff5eeebfeeecddc.........
    f55ede1fddecdc..........
    .f5eeedddedccc..........
    ..feeeeeeedde...........
    ...f2222eeee............
    ...f2222e2f.............
    ...feeee55f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
HeMan.setPosition(10, 300)
scene.cameraFollowSprite(HeMan)
controller.moveSprite(HeMan, 150, 0)
HeMan.ay = 350
