controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (0 == HeMan.vy) {
        HeMan.vy += -200
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite, location) {
    game.over(true)
})
sprites.onDestroyed(SpriteKind.Player, function (sprite) {
    info.changeScoreBy(1)
})
let HeMan: Sprite = null
let Light_rays = sprites.createProjectileFromSide(assets.image`He-Man Sword`, 50, 50)
scene.setBackgroundColor(15)
tiles.setTilemap(tilemap`level1`)
HeMan = sprites.create(img`
    ........................
    ....ffffff..............
    ..ff5555f5f.............
    .ff5555f555f............
    .f555ff55555f..ff.......
    .ffff5555555fff1f.......
    .f5555ffff55f111f.......
    fffffffeeeff111f........
    ff55ee1fdde111f.........
    f555dd1fdde11f..........
    .f55edddddefff..........
    ..ffee22dddef...........
    ...f2222ddff............
    ...f2222e2f.............
    ...f222255f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
HeMan.setPosition(10, 300)
scene.cameraFollowSprite(HeMan)
controller.moveSprite(HeMan, 150, 0)
HeMan.ay = 350
info.setLife(3)
info.setScore(0)
